import React from 'react';

export const metadata = {
    title: 'Profile',
    description: 'Generated by create next app',
}

const ProfilePage = () => {
    return (
        <div>
            profile page
        </div>
    );
};

export default ProfilePage;