// 'use client'

import Link from 'next/link';
// import { useRouter } from 'next/navigation';
import React from 'react';


// only workable in server components
export const metadata = {
    title: 'About',
    description: 'Generated by create next app',
}

// const blogs = [
//     {
//         id: 1,
//         year: 2016,
//         title: "title 1"
//     },
//     {
//         id: 2,
//         year: 2016,
//         title: "title 2"
//     },
//     {
//         id: 3,
//         year: 2016,
//         title: "title 3"
//     },
//     {
//         id: 4,
//         year: 2016,
//         title: "title 4"
//     },
// ]

const BlogPage = async () => {

    const res = await fetch("https://jsonplaceholder.typicode.com/posts", {
        cache: "force-cache"
    });
    const blogs = await res.json();

    // const router = useRouter(); // import from navigation

    return (
        <div className='container mx-auto'>
            {
                blogs.map(({ id, body, title }) => (

                    // recommended is create a client component for button
                    <div className='border border-blue-500 my-6 p-8' key={id}>
                        <h2 className='text-2xl'>{id}. {title}</h2>
                        <p>{body}</p>
                        <Link className='inline-block mt-5' href={`/blogs/${id}`}>
                            <button className='text-white px-2 py-1 bg-blue-500'>Details</button>
                        </Link>
                    </div>
                ))
            }
        </div>
    );
};

export default BlogPage;