// 'use client'

import Link from 'next/link';
// import { useRouter } from 'next/navigation';
import React from 'react';


// only workable in server components
export const metadata = {
    title: 'About',
    description: 'Generated by create next app',
}

const blogs = [
    {
        id: 1,
        year: 2016,
        title: "title 1"
    },
    {
        id: 2,
        year: 2016,
        title: "title 2"
    },
    {
        id: 3,
        year: 2016,
        title: "title 3"
    },
    {
        id: 4,
        year: 2016,
        title: "title 4"
    },
]

const page = () => {

    // const router = useRouter(); // import from navigation

    return (
        <div className='container mx-auto'>
            {
                blogs.map(({ id, year, title }) => (

                    // recommended is create a client component for button
                    <Link
                        className='block border border-blue-500 my-6 p-8'
                        key={id}
                        // href={`/blogs/${year}/${id}`}
                        href={{
                            pathname: `/blogs/${year}/${id}`,
                            query: {
                                title: title
                            }
                        }}
                    // onClick={() => router.push(`/blogs/${year}/${id}?title=${title}`)}
                    >
                        {title}
                    </Link>
                ))
            }
        </div>
    );
};

export default page;