import Navbar from '@/components/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hello Next.js',
  description: 'Generated by create next app',
}

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <nav>
          <a href="">Home</a>
          <a href="">About</a>
        </nav> */}
        {children}
        {/* <footer>This is footer</footer> */}
      </body>
    </html>
  )
}
export default RootLayout;